// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: todo.sql

package database

import (
	"context"
)

const findAllTodos = `-- name: FindAllTodos :many
SELECT id, title, description, status, created_at, updated_at from todos
`

func (q *Queries) FindAllTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, findAllTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
