definitions:
  todo.TodoModel:
    properties:
      description:
        type: string
      id:
        type: integer
      status:
        type: boolean
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /todos:
    get:
      consumes:
      - application/json
      description: Retrieve all todos from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/todo.TodoModel'
            type: array
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List all todos
      tags:
      - todos
swagger: "2.0"
